Mvg development
AvailLang/Avail pull request #235
Opened 2022-12-24 21:52 UTC by markATavail

Show phrase structure in editor.  This will need to be rebased after @richATavail 's PR merges, but I think the conflicts will be very minor.

2022-12-25 01:46 UTC, richATavail requested changes
I'm not familiar with how a lot of the work in this commit is put together, so I focused more on things I could identify as requiring attention in a more localized manner.

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/MessageSplitter.kt
>  		}
Are you trying to overwrite `group` with the contents in the `apply` block? 
The `Group` constructed  inside the `apply` block is just being thrown away and `group` preserves its previous value.

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/MessageSplitter.kt
> +		 * cached in an [LRUCache].  Since the [messageName] is used as a key in
You reference the value parameter, `messageName`, in a document link but you do not provide an `@param` comment description for `messageName`. When clicked through in the IDE, it provides no information other than type information.

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/MessageSplitterTokenizer.kt
> +	private var startInName = 1
The field name has changed which implies its usage/purpose has changed, however the comment has not been updated. Is the comment still accurate?

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/NumberedChoice.kt
> +	private val alternation: Alternation,
Missing constructor comments.

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/Optional.kt
>   *   The position of the group or token in the message name.
Another place where the parameter name has changed but the comment describing it has not. Is this just a more accurate name or does the comment need to be updated?

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/RawKeywordTokenArgument.kt
> +	pastEndInName: Int,
missing constructor comment

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/RawLiteralTokenArgument.kt
> +	pastEndInName: Int,
missing constructor comment

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/RawTokenArgument.kt
> +	pastEndInName: Int,
missing constructor comment

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/SectionCheckpoint.kt
> +	pastEndInName: Int,
missing constructor comment

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/Sequence.kt
> +	pastEndInName: Int,
missing constructor comment

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/Simple.kt
> +	pastEndInName: Int,
missing constructor comment

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/compiler/splitter/VariableQuote.kt
> +	pastEndInName: Int,
missing constructor comment

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/descriptor/phrases/SendPhraseDescriptor.kt
> +		 *   with parts of the method name itself, not the arguments.
Duplicate `@param` comment for `consumedTokens`.

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/utility/Strings.kt
> +	fun String.escapedForHTML() = buildString {
Add doc comments.

2022-12-25 01:46 UTC, richATavail commented on avail/src/main/kotlin/avail/anvil/Styles.kt
> +		val tokenIndexInName: Int)
Add `@property` comments for these.

2022-12-25 04:46 UTC, markATavail commented on avail/src/main/kotlin/avail/anvil/Styles.kt
>  						}
You'll like this.  I realized this was a reduce pattern, so I was able to shrink it to:
```
						val combined = styles
							.map(::StyleAspects)
							.reduce(StyleAspects::plus)
```

2022-12-26 05:32 UTC, markATavail commented on avail/src/main/kotlin/avail/compiler/CompilationContext.kt
> +			//atomName = atomName ?: stringFrom("(${phrase.phraseKind.name})")
Removed it, and simplified some earlier logic that's no longer needed.

2023-01-11 01:09 UTC, markATavail commented on avail/src/main/kotlin/avail/anvil/AvailEditor.kt
> +		val parseStructureListScroll = parseStructureList.scroll()
Moved it to its own window.

2023-01-11 03:10 UTC, toddATavail approved these changes
This looks incredibly good overall, and I'm going to merge it. But there are some clear bugs in `MessageSplitter` related to misuse of `apply`. @richATavail found one, and I found a second one. I might actually patch these up myself when I merge your branch into mine, but you should probably independently fix it anyway, in case I don't remember.

2023-01-11 03:10 UTC, toddATavail commented on avail/src/main/kotlin/avail/utility/CollectionExtensions.kt
> +}
Neat utility function. This is the one that you mentioned to me earlier, I think.

2023-01-11 03:10 UTC, toddATavail commented on avail/src/main/kotlin/avail/utility/ObjectTracer.kt
> +			theClass.iterableWith { it.superclass }.forEach { eachCls ->
Nice usage of the new utility also.

2023-01-11 03:10 UTC, merged