Code splitting ready for prime time
AvailLang/Avail pull request #315
Opened 2023-12-20 00:36 UTC by markATavail

Splitting is stable, and has run the Avail tests thousands of times.  There is
a glitch that happens ever few hundred runs related to `Acquire_` on an
Avail mutex, but it's unclear when this problem surfaced.

2023-12-22 00:38 UTC, toddATavail requested changes
I had small quibbles with your comments (or lack thereof) occasionally, and questions about some TODOs, but your techniques and logic look solid. Glad we have tests to prove general correctness, though! Would be extraordinarily hard by eye!

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/L2Instruction.kt
> +	fun interestingConditions(): List<L2SplitCondition> =
This really needs to be documented. It's practically criminal that I don't know what's interesting about them. Seems really important to the narrative.

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_GREATER_THAN_CONSTANT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_GREATER_THAN_OBJECT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_GREATER_THAN_OR_EQUAL_TO_CONSTANT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_GREATER_THAN_OR_EQUAL_TO_OBJECT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_LESS_THAN_CONSTANT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_LESS_THAN_OBJECT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_LESS_THAN_OR_EQUAL_TO_CONSTANT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_LESS_THAN_OR_EQUAL_TO_OBJECT.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_OBJECTS_EQUAL.kt
> +	//TODO override emit...
Is this `TODO` concerning?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_UNBOX_INT.kt
> +			?: L2SemanticUnboxedInt(source.semanticValue())
Based on the comment, maybe this needs to be factored into a named operation? Or is this the only place where you need to do this?

2023-12-22 00:38 UTC, toddATavail commented on avail/src/main/kotlin/avail/optimizer/L2Optimizer.kt
> +		}
This looks like it should be removed or conditionalized in some way.

2024-03-17 21:45 UTC, markATavail commented on avail/src/main/kotlin/avail/interpreter/levelTwo/operation/L2_JUMP_IF_OBJECTS_EQUAL.kt
> +	//TODO override emit...
This and some related comments have been obviated by completely rewriting the conditional branch instruction hierarchy, specifically introducing NumericCompare as a helper.

2024-07-23 16:02 UTC, toddATavail approved these changes
There's a lot here, but I glanced at most everything. I will have to take your word (and test results) that every here is ready. We ought to fix the 2x performance regression, though; it certainly wasn't the goal for code splitting to be a _de_-optimization.

2024-07-23 16:15 UTC, merged